### ISSUE TITLE
您好，发言比例用点来表示对于非等间距并不友好，因此建议更换

### ISSUE THREAD

**Issue by VentusMego** [maxwellzh/CRAQ#1]
> 发送次数|                                                            |用户名
--------|                                                            |----------
48      |····························································|xxx
40      |··················································          |xxx
36      |·············································               |xxx
22      |···························                                 |xxx
18      |······················                                      |xxx
15      |··················                                          |xxx
14      |·················                                           |xxx
11      |·············                                               |xxx
5       |······                                                      |xxx
5       |······                                                      |xxx
4       |·····                                                       |xxx
3       |···                                                         |xxx
2       |··                                                          |xxx
2       |··                                                          |xxx
2       |··                                                          |xxx
2       |··                                                          |xxx
1       |·                                                           |xxx
1       |·                                                           |xxx
1       |·                                                           |xxx

建议发言比例更换为如下所示：
> ▓▓▓▓▓▓░░░░░░░░░ 41%

**Comment by maxwellzh** [comment]
之前没有注意`·`的宽度，最新的release已经替换为`#`。
尝试了你建议的`▓▓▓▓▓▓░░░░░░░░░ 41%`，在命令行环境下看起来效果不太好。
